Repository futureleadersupc/waw-frontend-angular, pull requests merged in 2022-05, with the labels that each got.

#2 chore: setup Angular Material
  .idea/stylesheetLinters/stylelint.xml
  .stylelintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/custom-theme.scss
  src/index.html
  src/styles.css
Labels: chore, scope: deps, scope: linters

#3 chore(linters): ESLint scripts
  .vscode/settings.json
  package.json
Labels: chore, scope: linters

#4 chore(deps): Tailwind CSS
  .stylelintrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/styles.css
  tailwind.config.js
Labels: chore, scope: deps

#6 feat(auth): added initial auth service
  src/app/auth/model/user.ts
  src/app/auth/services/auth.service.spec.ts
  src/app/auth/services/auth.service.ts
Labels: enhancement, scope: auth

#5 feat(profile): initial version of profile component
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/profile/profile.component.css
  src/app/profile/profile.component.html
  src/app/profile/profile.component.spec.ts
  src/app/profile/profile.component.ts
Labels: enhancement, scope: profile

#7 feat: sign-up component
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/auth/pages/signup/signup.component.css
  src/app/auth/pages/signup/signup.component.html
  src/app/auth/pages/signup/signup.component.spec.ts
  src/app/auth/pages/signup/signup.component.ts
Labels: enhancement

#8 feat(ui): sign-in component
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/auth/pages/signin/signin.component.css
  src/app/auth/pages/signin/signin.component.html
  src/app/auth/pages/signin/signin.component.spec.ts
  src/app/auth/pages/signin/signin.component.ts
Labels: enhancement, scope: ui

#9 chore(ide): improve file nesting rules for vscode
  .vscode/settings.json
Labels: chore, scope: ide

#11 feat: added router links to components
  src/app/auth/pages/signin/signin.component.html
  src/app/auth/pages/signup/signup.component.html
Labels: enhancement

#12 test: fix imports for tests
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/auth/pages/signin/signin.component.spec.ts
  src/app/auth/pages/signup/signup.component.spec.ts
  src/app/auth/services/auth.service.spec.ts
  src/app/profile/profile.component.spec.ts
Labels: tests

#13 chore: update multiple settings
  .eslintrc.json
  .gitattributes
  .github/workflows/reviewdog.yml
  .github/workflows/tests.yml
  .vscode/settings.json
  README.md
  package.json
  src/app/auth/pages/signin/signin.component.ts
  src/app/auth/pages/signup/signup.component.ts
  src/app/auth/services/auth.service.ts
Labels: chore

#14 chore(sync): initial setup of fake API file sync
  .github/sync.yml
Labels: chore, scope: sync

#16 chore(deps): setup json-server
  .vscode/launch.json
  .vscode/tasks.json
  package-lock.json
  package.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/environments/model.ts
Labels: chore, scope: deps

#10 feat(ui): jobs administrator
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/common/model/column-definition.ts
  src/app/jobs/model/job-offer.ts
  src/app/jobs/pages/jobs/jobs.component.css
  src/app/jobs/pages/jobs/jobs.component.html
  src/app/jobs/pages/jobs/jobs.component.spec.ts
  src/app/jobs/pages/jobs/jobs.component.ts
  src/app/jobs/services/jobs.service.spec.ts
  src/app/jobs/services/jobs.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: scope: service, scope: ui

#17 refactor(auth): full rewrite of AuthService
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/auth/hooks/use-user.ts
  src/app/auth/model/user.ts
  src/app/auth/pages/signin/signin.component.html
  src/app/auth/pages/signin/signin.component.ts
  src/app/auth/services/auth.service.ts
  src/app/auth/services/projects.service.spec.ts
  src/app/auth/services/projects.service.ts
  src/app/common/services/base.service.spec.ts
  src/app/common/services/base.service.ts
  src/app/common/utils/types.ts
  src/app/core/pages/profile/profile.component.css
  src/app/core/pages/profile/profile.component.html
  src/app/core/pages/profile/profile.component.spec.ts
  src/app/core/pages/profile/profile.component.ts
  src/app/profile/profile.component.html
  src/app/profile/profile.component.ts
Labels: refactor, scope: auth

#23 feat(ui): job offers version 2 implemented
  src/app/app.module.ts
  src/app/jobs/pages/jobs/jobs.component.html
  src/app/jobs/pages/jobs/jobs.component.ts
Labels: enhancement

#24 feat(ui): jobs search component for job applications
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/jobs/components/job-confirmation-dialog/job-confirmation-dialog.component.css
  src/app/jobs/components/job-confirmation-dialog/job-confirmation-dialog.component.html
  src/app/jobs/components/job-confirmation-dialog/job-confirmation-dialog.component.spec.ts
  src/app/jobs/components/job-confirmation-dialog/job-confirmation-dialog.component.ts
  src/app/jobs/pages/jobs-search/jobs-search.component.css
  src/app/jobs/pages/jobs-search/jobs-search.component.html
  src/app/jobs/pages/jobs-search/jobs-search.component.spec.ts
  src/app/jobs/pages/jobs-search/jobs-search.component.ts
Labels: enhancement, scope: ui

#20 feat(ui): Initial implementation of base layout
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/auth/pages/changepassword/changepassword.component.html
  src/app/auth/pages/resetpassword/resetpassword.component.html
  src/app/auth/pages/signin/signin.component.html
  src/app/auth/pages/signup/signup.component.html
  src/app/common/components/footer/footer.component.css
  src/app/common/components/footer/footer.component.html
  src/app/common/components/footer/footer.component.spec.ts
  src/app/common/components/footer/footer.component.ts
  src/app/common/components/header/header.component.css
  src/app/common/components/header/header.component.html
  src/app/common/components/header/header.component.spec.ts
  src/app/common/components/header/header.component.ts
  src/app/common/model/navigation.ts
  src/app/common/services/responsive.service.spec.ts
  src/app/common/services/responsive.service.ts
  src/app/common/utils/breakpoints.ts
  src/index.html
  src/plugins/tailwind/mat-icon-sizes.js
  tailwind.config.js
Labels: enhancement, scope: ui

#26 feat(ui): job offers version 2.1 implemented
  src/app/jobs/pages/jobs/jobs.component.html
Labels: enhancement

#27 feat(ui): home page version 2
  src/app/auth/model/user.ts
  src/app/core/pages/profile/profile.component.html
  src/app/core/pages/profile/profile.component.ts
  src/app/core/utils/months.ts
Labels: scope: ui

#28 feat(ui): add searchbar handler
  src/app/common/components/header/header.component.html
  src/app/common/components/header/header.component.ts
Labels: enhancement, scope: ui
